# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI-AI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
import lp_recognition

class Ui_MainWindow(object):
    def __init__(self):
        self.link_img = None  # Khởi tạo thuộc tính để lưu link ảnh
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1117, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name1 = QtWidgets.QLabel(self.centralwidget)
        self.name1.setGeometry(QtCore.QRect(20, 10, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name1.setFont(font)
        self.name1.setTextFormat(QtCore.Qt.PlainText)
        self.name1.setObjectName("name1")
        self.name2 = QtWidgets.QLabel(self.centralwidget)
        self.name2.setGeometry(QtCore.QRect(20, 50, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name2.setFont(font)
        self.name2.setObjectName("name2")
        self.name3 = QtWidgets.QLabel(self.centralwidget)
        self.name3.setGeometry(QtCore.QRect(20, 80, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name3.setFont(font)
        self.name3.setObjectName("name3")
        self.pjname = QtWidgets.QLabel(self.centralwidget)
        self.pjname.setGeometry(QtCore.QRect(450, 100, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.pjname.setFont(font)
        self.pjname.setAlignment(QtCore.Qt.AlignCenter)
        self.pjname.setObjectName("pjname")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(800, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Ketqua = QtWidgets.QLineEdit(self.centralwidget)
        self.Ketqua.setGeometry(QtCore.QRect(750, 500, 191, 41))
        self.Ketqua.setText("")
        self.Ketqua.setObjectName("Ketqua")
        self.BTN_Start = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_Start.setGeometry(QtCore.QRect(500, 550, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BTN_Start.setFont(font)
        self.BTN_Start.setObjectName("BTN_Start")
        self.BTN_Reset = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_Reset.setGeometry(QtCore.QRect(790, 550, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BTN_Reset.setFont(font)
        self.BTN_Reset.setObjectName("BTN_Reset")
        self.BTN_Upload = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_Upload.setGeometry(QtCore.QRect(220, 550, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BTN_Upload.setFont(font)
        self.BTN_Upload.setObjectName("BTN_Upload")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 210, 461, 291))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(2)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 220, 431, 251))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setLineWidth(2)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 21))
        self.menubar.setObjectName("menubar")
        self.menuNh_n_di_n_bi_n_s_project_cu_i_k = QtWidgets.QMenu(self.menubar)
        self.menuNh_n_di_n_bi_n_s_project_cu_i_k.setObjectName("menuNh_n_di_n_bi_n_s_project_cu_i_k")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuNh_n_di_n_bi_n_s_project_cu_i_k.menuAction())
        
        # Kết nối các nút
        self.BTN_Upload.clicked.connect(self.linkto)
        self.BTN_Reset.clicked.connect(self.clear)
        self.BTN_Start.clicked.connect(self.ketqua)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name1.setText(_translate("MainWindow", "Nguyễn Huỳnh Thanh Phúc - 22119212"))
        self.name2.setText(_translate("MainWindow", "Lê Hồng Phong - 22119210"))
        self.name3.setText(_translate("MainWindow", "Lê Trí Bình An - 22119160"))
        self.pjname.setText(_translate("MainWindow", "NHẬN DIỆN BIỂN SỐ"))
        self.label.setText(_translate("MainWindow", "Biển số cần nhận dạng"))
        self.label_2.setText(_translate("MainWindow", "Kết quả"))
        self.BTN_Start.setText(_translate("MainWindow", "Start"))
        self.BTN_Reset.setText(_translate("MainWindow", "Reset"))
        self.BTN_Upload.setText(_translate("MainWindow", "Upload"))
        self.menuNh_n_di_n_bi_n_s_project_cu_i_k.setTitle(_translate("MainWindow", "Nhận diện biển số_project cuối kỳ"))

    def linkto(self):
        # Mở hộp thoại chọn tệp
        link, _ = QFileDialog.getOpenFileName(
            None, "Select Image", "", "Images (*.png *.jpg *.jpeg *.bmp *.gif)"
        )
        
        if link:
            self.link_img = link
            # Hiển thị ảnh trong label_3
            pixmap = QPixmap(link)
            self.label_3.setPixmap(pixmap)
            self.label_3.setScaledContents(True)
            

    
    def clear(self):
        # Đặt lại các thông tin hiển thị
        self.label_3.clear()  # Xóa ảnh trong QLabel
        self.Ketqua.clear()  # Xóa nội dung QLineEdit
        self.label_4.clear()  # Xóa nội dung QLabel khác (nếu cần)
        lp_recognition.cleanTemp()
        self.link_img = None

    def ketqua(self):
        if self.link_img != None:
            self.Ketqua.setText(lp_recognition.MainProcess(self.link_img))
            pixmap = QPixmap(f'{lp_recognition.temp}/Bien0.jpg')
            self.label_4.setPixmap(pixmap)
            self.label_4.setScaledContents(True)
        else:
            self.Ketqua.setText("Vui lòng nhập ảnh!")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
